// Package fixture holds the bundled default media.
//
// Provenance: a synthetic test pattern generated by scripts/gen-fixture.sh. It
// contains no third-party footage and is redistributable under this
// repository's MIT licence. It is a minimal default for self-tests and for
// consumers with no media of their own; it is not representative of real camera
// output.
package fixture

import _ "embed"

//go:embed fixture.ts
var data []byte

// Bytes returns the bundled MPEG-TS fixture. The returned slice is the
// package-level embedded data itself, not a copy; every call returns the same
// backing array. Callers must not mutate it.
func Bytes() []byte { return data }
