#!/usr/bin/env bash
# Regenerates the bundled media fixtures.
#
# Provenance: both fixtures are synthetic test patterns generated by this
# script. They contain no third-party footage, so they are redistributable
# under this repository's MIT licence.
#
# This script documents where the committed fixtures came from. It is NOT a
# build step and it is NOT byte-reproducible: a different ffmpeg, libx264, or
# libx265 build will encode the same pattern to different bytes. The committed
# fixtures are authoritative. If you regenerate them and the properties
# asserted in internal/media/media_test.go change, update those constants
# deliberately and say why in the commit message.
#
# Generated with: ffmpeg 6.1.1
set -euo pipefail

out_dir="$(dirname "$0")/../internal/media/fixture"

# H.264, baseline profile: maximises decoder compatibility for a fixture whose
# whole job is to be consumed by arbitrary client code.
ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "testsrc2=size=320x240:rate=15" \
  -t 2 \
  -c:v libx264 -preset veryslow -crf 30 \
  -pix_fmt yuv420p \
  -g 15 -profile:v baseline -bf 0 \
  "$out_dir/fixture.ts"

# H.265. -bf 0 mirrors the H.264 fixture's deliberate choice: it keeps PTS equal
# to DTS, so introducing a second codec does not also introduce the first
# B-frame reordering the pump has ever served. That is worth testing, as its own
# change with its own reasoning.
#
# Note that libx265 defaults to an open GOP regardless, so keyframes after the
# first are CRA_NUT rather than IDR. That is not corrected here: it is realistic
# encoder behaviour, and internal/media/codec.go's adapter handles it.
#
# libx265 is required only to regenerate this fixture. The committed file is
# authoritative, so CI needs plain ffmpeg and never libx265.
ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "testsrc2=size=320x240:rate=15" \
  -t 2 \
  -c:v libx265 -preset veryslow -crf 30 \
  -pix_fmt yuv420p \
  -g 15 -bf 0 \
  "$out_dir/fixture_h265.ts"

for f in "$out_dir/fixture.ts" "$out_dir/fixture_h265.ts"; do
  echo "wrote $f ($(stat -c%s "$f") bytes)"
done
