#!/usr/bin/env bash
# Regenerates the bundled media fixture.
#
# Provenance: the fixture is a synthetic test pattern generated by this script.
# It contains no third-party footage, so it is redistributable under this
# repository's MIT licence.
#
# This script documents where the committed fixture came from. It is NOT a build
# step and it is NOT byte-reproducible: a different ffmpeg or libx264 build will
# encode the same pattern to different bytes. The committed fixture is
# authoritative. If you regenerate it and the properties asserted in
# internal/media/media_test.go change, update those constants deliberately and
# say why in the commit message.
#
# Generated with: ffmpeg 6.1.1
set -euo pipefail

out="$(dirname "$0")/../internal/media/fixture/fixture.ts"

ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "testsrc2=size=320x240:rate=15" \
  -t 2 \
  -c:v libx264 -preset veryslow -crf 30 \
  -pix_fmt yuv420p \
  -g 15 -profile:v baseline -bf 0 \
  "$out"

echo "wrote $out ($(stat -c%s "$out") bytes)"
